@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInsureConnect" as VersionedInsureConnect MODEL_COLOR
end box

[-> Model : undoInsureConnect()
activate Model

Model -> VersionedInsureConnect : undo()
activate VersionedInsureConnect

VersionedInsureConnect -> VersionedInsureConnect :resetData(ReadOnlyInsureConnect)
VersionedInsureConnect --> Model :
deactivate VersionedInsureConnect

[<-- Model
deactivate Model

@enduml
