@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":InsureConnectParser" as icp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> icp ++: parseCommand(commandText)
create ecp
icp -> ecp
icp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editPersonDescriptor
ec --> ecp --
ecp --> icp --: command
icp --> logic --: command

@enduml
